"""Bundled city-to-IANA-timezone lookup table.

Coverage is intentionally limited to ~200 common cities. A miss logs a friendly
"city not in table" error rather than falling back to network geocoding.

Keys are lower-cased. Spaces and hyphens are normalized away in the lookup
(``los angeles`` and ``los-angeles`` both resolve).
"""

from __future__ import annotations

# Lower-case normalized city names -> IANA zones.
CITY_TO_TZ: dict[str, str] = {
    # North America
    "new york": "America/New_York",
    "nyc": "America/New_York",
    "boston": "America/New_York",
    "philadelphia": "America/New_York",
    "washington": "America/New_York",
    "washington dc": "America/New_York",
    "atlanta": "America/New_York",
    "miami": "America/New_York",
    "orlando": "America/New_York",
    "tampa": "America/New_York",
    "charlotte": "America/New_York",
    "raleigh": "America/New_York",
    "pittsburgh": "America/New_York",
    "detroit": "America/Detroit",
    "cleveland": "America/New_York",
    "columbus": "America/New_York",
    "indianapolis": "America/Indiana/Indianapolis",
    "nashville": "America/Chicago",
    "memphis": "America/Chicago",
    "chicago": "America/Chicago",
    "milwaukee": "America/Chicago",
    "minneapolis": "America/Chicago",
    "st louis": "America/Chicago",
    "saint louis": "America/Chicago",
    "kansas city": "America/Chicago",
    "oklahoma city": "America/Chicago",
    "dallas": "America/Chicago",
    "houston": "America/Chicago",
    "austin": "America/Chicago",
    "san antonio": "America/Chicago",
    "new orleans": "America/Chicago",
    "denver": "America/Denver",
    "salt lake city": "America/Denver",
    "albuquerque": "America/Denver",
    "phoenix": "America/Phoenix",
    "tucson": "America/Phoenix",
    "las vegas": "America/Los_Angeles",
    "los angeles": "America/Los_Angeles",
    "la": "America/Los_Angeles",
    "san diego": "America/Los_Angeles",
    "san francisco": "America/Los_Angeles",
    "sf": "America/Los_Angeles",
    "sacramento": "America/Los_Angeles",
    "san jose": "America/Los_Angeles",
    "oakland": "America/Los_Angeles",
    "portland": "America/Los_Angeles",
    "seattle": "America/Los_Angeles",
    "anchorage": "America/Anchorage",
    "juneau": "America/Juneau",
    "honolulu": "Pacific/Honolulu",
    "toronto": "America/Toronto",
    "ottawa": "America/Toronto",
    "montreal": "America/Montreal",
    "quebec": "America/Montreal",
    "halifax": "America/Halifax",
    "winnipeg": "America/Winnipeg",
    "edmonton": "America/Edmonton",
    "calgary": "America/Edmonton",
    "vancouver": "America/Vancouver",
    "mexico city": "America/Mexico_City",
    "guadalajara": "America/Mexico_City",
    "monterrey": "America/Monterrey",
    "tijuana": "America/Tijuana",
    "cancun": "America/Cancun",
    # South America
    "havana": "America/Havana",
    "santo domingo": "America/Santo_Domingo",
    "san juan": "America/Puerto_Rico",
    "panama city": "America/Panama",
    "bogota": "America/Bogota",
    "lima": "America/Lima",
    "quito": "America/Guayaquil",
    "caracas": "America/Caracas",
    "la paz": "America/La_Paz",
    "santiago": "America/Santiago",
    "buenos aires": "America/Argentina/Buenos_Aires",
    "montevideo": "America/Montevideo",
    "asuncion": "America/Asuncion",
    "sao paulo": "America/Sao_Paulo",
    "rio de janeiro": "America/Sao_Paulo",
    "brasilia": "America/Sao_Paulo",
    "manaus": "America/Manaus",
    # Europe
    "reykjavik": "Atlantic/Reykjavik",
    "dublin": "Europe/Dublin",
    "london": "Europe/London",
    "edinburgh": "Europe/London",
    "manchester": "Europe/London",
    "glasgow": "Europe/London",
    "lisbon": "Europe/Lisbon",
    "porto": "Europe/Lisbon",
    "madrid": "Europe/Madrid",
    "barcelona": "Europe/Madrid",
    "seville": "Europe/Madrid",
    "valencia": "Europe/Madrid",
    "paris": "Europe/Paris",
    "marseille": "Europe/Paris",
    "lyon": "Europe/Paris",
    "nice": "Europe/Paris",
    "brussels": "Europe/Brussels",
    "amsterdam": "Europe/Amsterdam",
    "rotterdam": "Europe/Amsterdam",
    "the hague": "Europe/Amsterdam",
    "luxembourg": "Europe/Luxembourg",
    "zurich": "Europe/Zurich",
    "geneva": "Europe/Zurich",
    "bern": "Europe/Zurich",
    "milan": "Europe/Rome",
    "rome": "Europe/Rome",
    "naples": "Europe/Rome",
    "florence": "Europe/Rome",
    "venice": "Europe/Rome",
    "turin": "Europe/Rome",
    "vatican": "Europe/Vatican",
    "berlin": "Europe/Berlin",
    "munich": "Europe/Berlin",
    "hamburg": "Europe/Berlin",
    "frankfurt": "Europe/Berlin",
    "cologne": "Europe/Berlin",
    "vienna": "Europe/Vienna",
    "salzburg": "Europe/Vienna",
    "prague": "Europe/Prague",
    "warsaw": "Europe/Warsaw",
    "krakow": "Europe/Warsaw",
    "budapest": "Europe/Budapest",
    "bucharest": "Europe/Bucharest",
    "sofia": "Europe/Sofia",
    "athens": "Europe/Athens",
    "thessaloniki": "Europe/Athens",
    "belgrade": "Europe/Belgrade",
    "sarajevo": "Europe/Sarajevo",
    "zagreb": "Europe/Zagreb",
    "ljubljana": "Europe/Ljubljana",
    "copenhagen": "Europe/Copenhagen",
    "oslo": "Europe/Oslo",
    "stockholm": "Europe/Stockholm",
    "gothenburg": "Europe/Stockholm",
    "helsinki": "Europe/Helsinki",
    "tallinn": "Europe/Tallinn",
    "riga": "Europe/Riga",
    "vilnius": "Europe/Vilnius",
    "minsk": "Europe/Minsk",
    "moscow": "Europe/Moscow",
    "st petersburg": "Europe/Moscow",
    "saint petersburg": "Europe/Moscow",
    "kyiv": "Europe/Kyiv",
    "kiev": "Europe/Kyiv",
    "istanbul": "Europe/Istanbul",
    "ankara": "Europe/Istanbul",
    # Middle East & Africa
    "cairo": "Africa/Cairo",
    "alexandria": "Africa/Cairo",
    "casablanca": "Africa/Casablanca",
    "tunis": "Africa/Tunis",
    "algiers": "Africa/Algiers",
    "tripoli": "Africa/Tripoli",
    "lagos": "Africa/Lagos",
    "abuja": "Africa/Lagos",
    "accra": "Africa/Accra",
    "nairobi": "Africa/Nairobi",
    "addis ababa": "Africa/Addis_Ababa",
    "kampala": "Africa/Kampala",
    "dar es salaam": "Africa/Dar_es_Salaam",
    "kinshasa": "Africa/Kinshasa",
    "johannesburg": "Africa/Johannesburg",
    "cape town": "Africa/Johannesburg",
    "durban": "Africa/Johannesburg",
    "pretoria": "Africa/Johannesburg",
    "harare": "Africa/Harare",
    "lusaka": "Africa/Lusaka",
    "tel aviv": "Asia/Jerusalem",
    "jerusalem": "Asia/Jerusalem",
    "amman": "Asia/Amman",
    "beirut": "Asia/Beirut",
    "damascus": "Asia/Damascus",
    "baghdad": "Asia/Baghdad",
    "tehran": "Asia/Tehran",
    "riyadh": "Asia/Riyadh",
    "jeddah": "Asia/Riyadh",
    "mecca": "Asia/Riyadh",
    "dubai": "Asia/Dubai",
    "abu dhabi": "Asia/Dubai",
    "doha": "Asia/Qatar",
    "kuwait city": "Asia/Kuwait",
    "manama": "Asia/Bahrain",
    "muscat": "Asia/Muscat",
    # Asia
    "karachi": "Asia/Karachi",
    "islamabad": "Asia/Karachi",
    "lahore": "Asia/Karachi",
    "kabul": "Asia/Kabul",
    "tashkent": "Asia/Tashkent",
    "delhi": "Asia/Kolkata",
    "new delhi": "Asia/Kolkata",
    "mumbai": "Asia/Kolkata",
    "bombay": "Asia/Kolkata",
    "bangalore": "Asia/Kolkata",
    "bengaluru": "Asia/Kolkata",
    "hyderabad": "Asia/Kolkata",
    "chennai": "Asia/Kolkata",
    "kolkata": "Asia/Kolkata",
    "pune": "Asia/Kolkata",
    "ahmedabad": "Asia/Kolkata",
    "colombo": "Asia/Colombo",
    "kathmandu": "Asia/Kathmandu",
    "dhaka": "Asia/Dhaka",
    "yangon": "Asia/Yangon",
    "bangkok": "Asia/Bangkok",
    "phnom penh": "Asia/Phnom_Penh",
    "hanoi": "Asia/Ho_Chi_Minh",
    "ho chi minh city": "Asia/Ho_Chi_Minh",
    "saigon": "Asia/Ho_Chi_Minh",
    "vientiane": "Asia/Vientiane",
    "kuala lumpur": "Asia/Kuala_Lumpur",
    "singapore": "Asia/Singapore",
    "jakarta": "Asia/Jakarta",
    "bali": "Asia/Makassar",
    "denpasar": "Asia/Makassar",
    "manila": "Asia/Manila",
    "cebu": "Asia/Manila",
    "taipei": "Asia/Taipei",
    "hong kong": "Asia/Hong_Kong",
    "macau": "Asia/Macau",
    "beijing": "Asia/Shanghai",
    "shanghai": "Asia/Shanghai",
    "guangzhou": "Asia/Shanghai",
    "shenzhen": "Asia/Shanghai",
    "chengdu": "Asia/Shanghai",
    "xi an": "Asia/Shanghai",
    "seoul": "Asia/Seoul",
    "busan": "Asia/Seoul",
    "pyongyang": "Asia/Pyongyang",
    "tokyo": "Asia/Tokyo",
    "osaka": "Asia/Tokyo",
    "kyoto": "Asia/Tokyo",
    "yokohama": "Asia/Tokyo",
    "sapporo": "Asia/Tokyo",
    "ulaanbaatar": "Asia/Ulaanbaatar",
    "novosibirsk": "Asia/Novosibirsk",
    "vladivostok": "Asia/Vladivostok",
    # Oceania
    "perth": "Australia/Perth",
    "adelaide": "Australia/Adelaide",
    "darwin": "Australia/Darwin",
    "brisbane": "Australia/Brisbane",
    "sydney": "Australia/Sydney",
    "canberra": "Australia/Sydney",
    "melbourne": "Australia/Melbourne",
    "hobart": "Australia/Hobart",
    "auckland": "Pacific/Auckland",
    "wellington": "Pacific/Auckland",
    "christchurch": "Pacific/Auckland",
    "suva": "Pacific/Fiji",
    "port moresby": "Pacific/Port_Moresby",
    "guam": "Pacific/Guam",
    "tahiti": "Pacific/Tahiti",
    "papeete": "Pacific/Tahiti",
}


def normalize(city: str) -> str:
    """Lower-case and collapse separators so 'Los-Angeles' == 'los angeles'."""
    return " ".join(city.lower().replace("-", " ").replace("_", " ").split())


def lookup(city: str) -> str | None:
    return CITY_TO_TZ.get(normalize(city))
